###

//GET ALL STATES
GET http://localhost:3004/states/
###

//GET STATE BY STATE ID
GET http://localhost:3004/states/4
###

//CREATE DISTRICT
POST http://localhost:3004/districts/
Content-Type: application/json

{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}
###
//GET DISTRICT BY ID
GET http://localhost:3004/districts/100
###
//DELETE DISTRICT BY ID
DELETE http://localhost:3004/districts/50
###

//API 6: UPDATE DISTRICT
PUT http://localhost:3004/districts/100
Content-Type: application/json

{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}
###
//TO GET STATS
GET http://localhost:3004/states/6/stats/
###
//TO GET STATE OF DISTRICT
GET http://localhost:3004/districts/90/details/